---
- name: "Updating apt/repo cache"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt:
    upgrade: yes
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
  become: true
  become_method: sudo

- name: "Install apt packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - antiword
      - tesseract-ocr
      - python3.11-venv
      - virtualbox-guest-x11
      - remmina
      - golang
      - python3-pip
      - python3-venv
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - python3-pyqt5
      - terminator
      - python3-impacket
      - seclists
      - nuclei
    state: latest
  become: true
  become_method: sudo

- name: "Set GOROOT in zshrc for user kali"
  lineinfile:
    path: /home/kali/.zshrc
    line: 'export GOROOT=/usr/lib/go'
    state: present
    create: yes

- name: "Set GOPATH in zshrc for user kali"
  lineinfile:
    path: /home/kali/.zshrc
    line: 'export GOPATH=$HOME/go'
    state: present
    create: yes

- name: "Update GOPATH in zshrc for user kali"
  lineinfile:
    path: /home/kali/.zshrc
    line: 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin'
    state: present
    create: yes

- name: Ensure pipx PATH is configured globally
  command: sudo pipx ensurepath
  command: pipx ensurepath
  become: true
  
