---
# No playbook/play name here as this is a tasks file within a role

- name: Ensure prerequisites are installed
  apt:
    name:
      - apt-transport-https
      - wget
    state: present

- name: Download .deb files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  when: item.url is defined
  loop: "{{ deb_files }}"

- name: Install .deb packages
  apt:
    deb: "{{ item.dest }}"
  loop: "{{ deb_files }}"
