---
- name: Install impacket from github repository
  community.general.pipx:
    name: impacket
    state: present
    path: /usr/local/bin
    virtualenv: /usr/local/bin
    force: yes
    executable: /usr/local/bin/impacket
    extra_args: --no-cache-dir
    version: latest

  - name: Install certipy from github repository
    community.general.pipx:
      name: certipy
      state: present
      path: /usr/local/bin
      virtualenv: /usr/local/bin
      force: yes
      executable: /usr/local/bin/certipy
      extra_args: --no-cache-dir
      version: latest
  
  - name: Install Crosslinked from github repository
    community.general.pipx:
      name: crosslinked
      state: present
      path: /usr/local/bin
      virtualenv: /usr/local/bin
      force: yes
      executable: /usr/local/bin/crosslinked
      extra_args: --no-cache-dir
      version: latest
