---
- name: "Ensure pipx tools are installed"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: present
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/Porchetta-Industries/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'crosslinked', url: 'git+https://github.com/m8sec/CrossLinked.git' }

- name: "Upgrade pipx tools to latest version"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/Porchetta-Industries/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'crosslinked', url: 'git+https://github.com/m8sec/CrossLinked.git' }
