---
- name: Debug - Find python path in pipx environment
  command: "{{ ansible_env.PATH }} && which python"
  register: python_path
  - debug:
    var: python_path
    
- name: "Ensure pipx tools are installed"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: present
    executable: "{{ python_path.stdout  }}"  # Update path if needed
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/Porchetta-Industries/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly5k/Certipy.git' }
    - { name: 'crosslinked', url: 'git+https://github.com/m8sec/CrossLinked.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git'}

- name: "Upgrade pipx tools to latest version"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/Porchetta-Industries/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly5k/Certipy.git' }
    - { name: 'crosslinked', url: 'git+https://github.com/m8sec/CrossLinked.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git'}
