---
- name: Kali Linux Setup and Configuration
  hosts: localhost
  become: yes
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-system"
      users:
        - username: "{{ ansible_user_id}}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot
            - sny-security.snyk-vulnerability-scanner
